//! Generates a typed TypeScript HTTP client (`createApi(config)`) from the
//! `#[endpoint]` handlers, nested by the dotted endpoint name
//! (`"live.rtc.tracks.close"` -> `api.live.rtc.tracks.close`). The factory is
//! stateless, so it's safe to build per-request on the server with the incoming
//! `fetch` + cookies. Every method returns `Promise<Result<T, ApiError>>` —
//! transport, HTTP, and validation failures surface as `err(...)`, never throw.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

use super::backend::TypeScript;
use super::runtime::{CONFIG_BLOCK, QUERY_HELPER, REQUEST_HELPER, SEND_HELPER, VALIDATE_HELPER};
use crate::export::{ExportBackend, FieldType};
use crate::registry::EndpointMeta;
use crate::validator::ValidatorSchema;

/// The referenced type's name, if it's a named export (vs a builtin like `Json`).
fn named(ty: &FieldType) -> Option<&'static str> {
    match ty {
        FieldType::Named(name) => Some(*name),
        _ => None,
    }
}

/// A node in the client object tree: nested `groups` and leaf `methods`
/// (method name -> the rendered arrow function, which may span several lines).
#[derive(Default)]
struct Group {
    groups: BTreeMap<String, Group>,
    methods: BTreeMap<String, String>,
}

impl Group {
    fn insert(&mut self, parts: &[&str], method: String) {
        match parts {
            [last] => {
                self.methods.insert((*last).to_string(), method);
            }
            [head, rest @ ..] => {
                self.groups
                    .entry((*head).to_string())
                    .or_default()
                    .insert(rest, method);
            }
            [] => {}
        }
    }

    fn render(&self, out: &mut String, indent: usize) {
        let pad = "  ".repeat(indent);
        for (name, method) in &self.methods {
            let lines: Vec<&str> = method.lines().collect();
            let last = lines.len().saturating_sub(1);
            for (i, line) in lines.iter().enumerate() {
                let label = if i == 0 { format!("{name}: ") } else { String::new() };
                let comma = if i == last { "," } else { "" };
                let _ = writeln!(out, "{pad}{label}{line}{comma}");
            }
        }

        for (name, group) in &self.groups {
            let _ = writeln!(out, "{pad}{name}: {{");
            group.render(out, indent + 1);
            let _ = writeln!(out, "{pad}}},");
        }
    }
}

/// Write `<out_dir>/client.ts` from the registered endpoints. `types_prefix` is
/// the import prefix for the type modules (e.g. `"."` or `"$lib/types"`).
pub fn generate_client(out_dir: &str, types_prefix: &str) -> anyhow::Result<()> {
    let mut endpoints: Vec<&EndpointMeta> = inventory::iter::<EndpointMeta>.into_iter().collect();
    endpoints.sort_by_key(|e| e.name);

    let schema_names: BTreeSet<String> = inventory::iter::<ValidatorSchema>
        .into_iter()
        .map(|s| s.name.to_string())
        .collect();

    let mut imports: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut schema_imports: BTreeSet<String> = BTreeSet::new();
    let mut root = Group::default();
    let mut needs_query = false;

    let paths = crate::export::type_paths();
    for endpoint in &endpoints {
        for type_ref in [&endpoint.request, &endpoint.query, &endpoint.response].into_iter().flatten() {
            let Some(name) = named(type_ref.ty) else { continue };
            let Some(&path) = paths.get(name) else { continue };
            imports
                .entry(module_specifier(path, types_prefix))
                .or_default()
                .insert(name.to_string());
        }
        if endpoint.query.is_some() {
            needs_query = true;
        }

        let validated = endpoint.request.as_ref().and_then(|r| {
            named(r.ty)
                .filter(|n| schema_names.contains(*n))
                .map(|n| format!("{n}Schema"))
        });

        if let Some(schema) = &validated {
            schema_imports.insert(schema.clone());
        }

        let parts: Vec<&str> = endpoint.name.split('.').collect();
        root.insert(&parts, render_method(endpoint, validated.as_deref()));
    }

    let needs_validate = !schema_imports.is_empty();

    let mut out = String::from("// Generated by orm from #[endpoint] handlers. Do not edit.\n");

    for (module, names) in &imports {
        let _ = writeln!(out, "import type {{ {} }} from \"{module}\";", comma_separated(names));
    }

    let _ = writeln!(out, "import {{ ok, err, result, type Result }} from \"$lib/lib/result\";");

    if needs_validate {
        let _ = writeln!(out, "import * as v from \"valibot\";");
        let _ = writeln!(out, "import {{ {} }} from \"$lib/schema/schemas\";", comma_separated(&schema_imports));
    }

    out.push_str(CONFIG_BLOCK);
    out.push_str("\nexport function createApi(config: ApiConfig = {}) {\n");
    out.push_str(REQUEST_HELPER);
    if needs_validate {
        out.push_str(VALIDATE_HELPER);
        out.push_str(SEND_HELPER);
    }
    if needs_query {
        out.push_str(QUERY_HELPER);
    }
    out.push_str("\n  return {\n");
    root.render(&mut out, 2);
    out.push_str("  };\n}\n\n");
    out.push_str("export type Api = ReturnType<typeof createApi>;\n");

    let client_path = Path::new(out_dir).join("service").join("client.ts");
    if let Some(parent) = client_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(client_path, out)?;
    Ok(())
}

const RESULT_RUNTIME: &str = r#"// Generated by orm. Do not edit.
export type Result<T, E> =
  | { err: false; value: T }
  | { err: true; error: E };

export function ok<T>(value: T): Result<T, never> {
  return { err: false, value };
}

export function err<E>(error: E): Result<never, E> {
  return { err: true, error };
}

export async function result<T>(fn: () => Promise<T>): Promise<Result<T, unknown>> {
  try {
    return ok(await fn());
  } catch (error) {
    return err(error);
  }
}
"#;

/// Write `<out_dir>/lib/result.ts`, the Result runtime the generated client imports.
pub fn generate_result(out_dir: &str) -> anyhow::Result<()> {
    let path = Path::new(out_dir).join("lib").join("result.ts");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, RESULT_RUNTIME)?;
    Ok(())
}

/// The arrow function for one endpoint, formatted across a couple of lines:
///
/// ```ts
/// create: (body: CreateSessionRequest): Promise<Result<LiveSession, ApiError>> =>
///   send<LiveSession>("POST", `/live/sessions`, CreateSessionRequestSchema, body),
/// ```
fn render_method(endpoint: &EndpointMeta, validated: Option<&str>) -> String {
    let mut args: Vec<String> = path_params(endpoint.path)
        .iter()
        .map(|p| format!("{p}: string"))
        .collect();

    if let Some(request) = &endpoint.request {
        args.push(format!("body: {}", TypeScript.type_expr(request.ty)));
    }
    if let Some(query) = &endpoint.query {
        args.push(format!("query: {}", TypeScript.type_expr(query.ty)));
    }

    let returns = endpoint
        .response
        .as_ref()
        .map(|r| TypeScript.type_expr(r.ty))
        .unwrap_or_else(|| "void".to_string());

    let path = endpoint.path.replace('{', "${");
    let url = match endpoint.query {
        Some(_) => format!("`{path}` + toQuery(query)"),
        None => format!("`{path}`"),
    };

    let method = endpoint.method;
    let signature = format!("({}): Promise<Result<{returns}, ApiError>> =>", args.join(", "));

    let call = match validated {
        Some(schema) => format!("send<{returns}>(\"{method}\", {url}, {schema}, body)"),
        None if endpoint.request.is_some() => format!("request<{returns}>(\"{method}\", {url}, body)"),
        None => format!("request<{returns}>(\"{method}\", {url})"),
    };

    format!("{signature}\n  {call}")
}

fn comma_separated(names: &BTreeSet<String>) -> String {
    names
        .iter()
        .cloned()
        .collect::<Vec<_>>()
        .join(", ")
}

/// `api/live.ts` -> `<prefix>/api/live` (e.g. `./api/live` or `$lib/types/api/live`).
fn module_specifier(path: &str, prefix: &str) -> String {
    format!("{}/{}", prefix, path.trim_end_matches(".ts"))
}

/// Names of `{param}` segments in a route path, in order.
fn path_params(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|seg| seg.strip_prefix('{').and_then(|s| s.strip_suffix('}')))
        .map(str::to_string)
        .collect()
}
