use std::marker::PhantomData;

use anyhow::{Context, Result, bail};
use tokio_postgres::types::ToSql;

use super::client::Executor;
use super::join::{Join, ReadQuery};
use super::{FilterGroup, FilterOp, FilterValue, Insert, JoinOn, QueryOptions, QuerySort, SortOrder, UpdateValues};
use crate::FromRow;

/// Relation metadata generated by `#[table_type]` and `#[view_type]`.
pub trait QueryModel: FromRow {
    const RELATION: &'static str;
    const COLUMNS: &'static [&'static str];
}

/// Writable relation metadata generated only by `#[table_type]`.
/// A read-only model (including a generated view) cannot be mutated.
///
/// ```compile_fail
/// use orm::query::{QueryBuilderExt, QueryModel};
/// fn update_view<V: QueryModel>(client: &tokio_postgres::Client) {
///     client.update::<V>();
/// }
/// ```
pub trait TableModel: QueryModel {}

/// Fluent queries on a pool, pooled client, PostgreSQL client, or transaction.
/// Builders execute only when a terminal method is awaited.
pub trait QueryBuilderExt: Executor {
    fn select<M: QueryModel>(&self) -> Select<'_, Self, M> {
        Select {
            client: self,
            options: QueryOptions::new(),
            read: ReadQuery::default(),
            model: PhantomData,
        }
    }

    fn insert<M: TableModel>(&self) -> Insert<'_, Self, M> {
        Insert::new(self)
    }

    fn update<M: TableModel>(&self) -> Update<'_, Self, M> {
        Update {
            client: self,
            options: QueryOptions::new(),
            values: UpdateValues::new(),
            all_rows: false,
            model: PhantomData,
        }
    }

    fn delete<M: TableModel>(&self) -> Delete<'_, Self, M> {
        Delete {
            client: self,
            options: QueryOptions::new(),
            all_rows: false,
            model: PhantomData,
        }
    }
}

impl<C: Executor + ?Sized> QueryBuilderExt for C {}

/// A SELECT of a table or view's declared columns.
#[must_use = "a query builder does nothing until a terminal method is awaited"]
pub struct Select<'a, C: ?Sized, M, R = M> {
    client: &'a C,
    options: QueryOptions,
    read: ReadQuery,
    model: PhantomData<fn() -> (M, R)>,
}

/// An atomic UPDATE with bound assignments and predicates.
#[must_use = "a query builder does nothing until execute or returning is awaited"]
pub struct Update<'a, C: ?Sized, M> {
    client: &'a C,
    options: QueryOptions,
    values: UpdateValues,
    all_rows: bool,
    model: PhantomData<fn() -> M>,
}

/// A DELETE requiring a predicate or explicit `all_rows()`.
#[must_use = "a query builder does nothing until execute or returning is awaited"]
pub struct Delete<'a, C: ?Sized, M> {
    client: &'a C,
    options: QueryOptions,
    all_rows: bool,
    model: PhantomData<fn() -> M>,
}

macro_rules! predicates {
    () => {
        /// Adds an AND predicate. Like `QueryOptions::filter`, an optional
        /// `None` value omits the predicate; use `where_null` for SQL NULL.
        pub fn where_<V: FilterValue>(mut self, field: impl Into<String>, op: FilterOp, value: V) -> Self {
            self.options = self.options.filter(field, op, value);
            self
        }

        /// Adds a parenthesized AND/OR group, ANDed with other predicates.
        pub fn where_group(mut self, group: FilterGroup) -> Self {
            self.options = self.options.filter_group(group);
            self
        }

        pub fn where_null(mut self, field: impl Into<String>) -> Self {
            self.options = self.options.is_null(field);
            self
        }

        pub fn where_not_null(mut self, field: impl Into<String>) -> Self {
            self.options = self.options.is_not_null(field);
            self
        }

        /// Replaces the accumulated query options. Writes reject read-only
        /// controls; predicates added after this call extend these options.
        pub fn options(mut self, options: QueryOptions) -> Self {
            self.options = options;
            self
        }
    };
}

impl<'a, C: Executor + ?Sized, M: QueryModel, R: FromRow> Select<'a, C, M, R> {
    predicates!();

    pub fn alias(mut self, alias: impl Into<String>) -> Self {
        self.read.alias = Some(alias.into());
        self
    }

    pub fn inner_join<J: QueryModel>(mut self, alias: impl Into<String>, on: JoinOn) -> Self {
        self.read.joins.push(Join::new::<J>(alias, false, on));
        self
    }

    pub fn left_join<J: QueryModel>(mut self, alias: impl Into<String>, on: JoinOn) -> Self {
        self.read.joins.push(Join::new::<J>(alias, true, on));
        self
    }

    /// Selects explicit source-column/output-name pairs into a FromRow type.
    /// LEFT JOIN output fields must allow NULL where the join can miss.
    pub fn project<P: FromRow>(mut self, columns: &[(&str, &str)]) -> Select<'a, C, M, P> {
        self.read.projection = Some(
            columns.iter()
                .map(|(field, alias)| (field.to_string(), alias.to_string()))
                .collect()
        );

        Select {
            client: self.client,
            options: self.options,
            read: self.read,
            model: PhantomData,
        }
    }

    /// Replaces existing ordering. Use `then_order_by` for tie-breakers.
    pub fn order_by(mut self, field: impl Into<String>, order: SortOrder) -> Self {
        self.options = self.options.sort(QuerySort::new(field, order));
        self
    }

    pub fn then_order_by(mut self, field: impl Into<String>, order: SortOrder) -> Self {
        self.options = self.options.then_sort(QuerySort::new(field, order));
        self
    }

    pub fn limit(mut self, limit: u32) -> Self {
        self.options = self.options.limit(limit);
        self
    }

    pub fn offset(mut self, offset: u32) -> Self {
        self.options = self.options.offset(offset);
        self
    }

    /// Locks base-table rows only; retained within an explicit transaction.
    pub fn for_update(mut self) -> Self {
        self.options = self.options.for_update();
        self
    }

    /// Locks base-table rows only; retained within an explicit transaction.
    pub fn for_share(mut self) -> Self {
        self.options = self.options.for_share();
        self
    }

    pub async fn fetch_all(self) -> Result<Vec<R>> {
        let sql = self.read.sql::<M>(&self.options, false)?;
        query_models(self.client, &sql, &self.read.params(&self.options))
            .await
    }

    /// Counts matching joined rows before sorting/pagination, without row locks.
    /// One-to-many joins count duplicates, as SQL COUNT(*) does.
    pub async fn count(self) -> Result<i64> {
        let sql = self.read.sql::<M>(&self.options, true)?;
        let row = self.client.query_row(&sql, &self.read.params(&self.options))
            .await?;

        Ok(row.try_get("count")?)
    }

    /// Returns zero or one selected row, rejecting multiple matches.
    /// An explicit `limit(1)` selects the first row instead.
    pub async fn fetch_optional(self) -> Result<Option<R>> {
        let mut rows = self.fetch_all()
            .await?;

        if rows.len() > 1 {
            bail!("expected at most one row from {}", M::RELATION);
        }

        Ok(rows.pop())
    }

    /// Requires exactly one selected row. Never adds an implicit limit.
    pub async fn fetch_one(self) -> Result<R> {
        let sql = self.read.sql::<M>(&self.options, false)?;
        query_model(self.client, &sql, &self.read.params(&self.options))
            .await
    }
}

impl<C: Executor + ?Sized, M: TableModel> Update<'_, C, M> {
    predicates!();

    pub fn set<V: ToSql + Send + Sync + 'static>(mut self, field: impl Into<String>, value: V) -> Self {
        self.values = self.values.assign(field, value);
        self
    }

    pub fn add<V: ToSql + Send + Sync + 'static>(mut self, field: impl Into<String>, value: V) -> Self {
        self.values = self.values.add(field, value);
        self
    }

    pub fn subtract<V: ToSql + Send + Sync + 'static>(mut self, field: impl Into<String>, value: V) -> Self {
        self.values = self.values.subtract(field, value);
        self
    }

    pub fn set_null(mut self, field: impl Into<String>) -> Self {
        self.values = self.values.null(field);
        self
    }

    pub fn database_now(mut self, field: impl Into<String>) -> Self {
        self.values = self.values.database_now(field);
        self
    }

    /// Replaces the accumulated assignments with an existing update set.
    pub fn values(mut self, values: UpdateValues) -> Self {
        self.values = values;
        self
    }

    /// Explicitly permits updating every row. Cannot be combined with predicates.
    pub fn all_rows(mut self) -> Self {
        self.all_rows = true;
        self
    }

    fn sql(&self, returning: bool) -> Result<String> {
        let (assignments, next) = self.values.build(1, M::COLUMNS)?;
        let predicate = write_predicate::<M>(&self.options, self.all_rows, next)?;
        let mut sql = format!("UPDATE {} SET {}{}", M::RELATION, assignments, predicate);
        append_returning::<M>(&mut sql, returning);
        Ok(sql)
    }

    fn params(&self) -> Vec<&(dyn ToSql + Sync)> {
        let mut params = self.values.params();
        params.extend(self.options.filter_params());
        params
    }

    /// Executes without RETURNING and returns the affected row count.
    pub async fn execute(self) -> Result<u64> {
        let sql = self.sql(false)?;
        self.client
            .execute_statement(&sql, &self.params())
            .await
            .with_context(|| format!("Failed to update {}", M::RELATION))
    }

    /// Returns every updated row from the same atomic UPDATE statement.
    pub async fn returning(self) -> Result<Vec<M>> {
        let sql = self.sql(true)?;
        query_models(self.client, &sql, &self.params())
            .await
    }

    /// Requires one returned row. A cardinality error does not undo the write;
    /// use a unique predicate and an explicit transaction when needed.
    pub async fn returning_one(self) -> Result<M> {
        let sql = self.sql(true)?;
        query_model(self.client, &sql, &self.params())
            .await
    }
}

impl<C: Executor + ?Sized, M: TableModel> Delete<'_, C, M> {
    predicates!();

    /// Explicitly permits deleting every row. Cannot be combined with predicates.
    pub fn all_rows(mut self) -> Self {
        self.all_rows = true;
        self
    }

    fn sql(&self, returning: bool) -> Result<String> {
        let predicate = write_predicate::<M>(&self.options, self.all_rows, 1)?;
        let mut sql = format!("DELETE FROM {}{}", M::RELATION, predicate);
        append_returning::<M>(&mut sql, returning);
        Ok(sql)
    }

    /// Executes without RETURNING and returns the affected row count.
    pub async fn execute(self) -> Result<u64> {
        let sql = self.sql(false)?;
        self.client
            .execute_statement(&sql, &self.options.filter_params())
            .await
            .with_context(|| format!("Failed to delete from {}", M::RELATION))
    }

    /// Returns every deleted row from the same DELETE statement.
    pub async fn returning(self) -> Result<Vec<M>> {
        let sql = self.sql(true)?;
        query_models(self.client, &sql, &self.options.filter_params())
            .await
    }
}

fn validate_options<M: QueryModel>(options: &QueryOptions) -> Result<()> {
    for filter in options.groups.iter()
        .flat_map(|group| &group.filters)
    {
        validate_column::<M>(&filter.field)?;
        if filter.op.needs_value() != filter.value.is_some() {
            bail!("invalid value for filter on `{}`", filter.field);
        }
    }

    if let Some(field) = &options.sort_by {
        validate_column::<M>(field)?;
    }

    for sort in &options.secondary_sorts {
        validate_column::<M>(&sort.field)?;
    }

    Ok(())
}

pub(crate) fn validate_column<M: QueryModel>(field: &str) -> Result<()> {
    if !super::builder::is_identifier(field) || !M::COLUMNS.contains(&field) {
        bail!("unknown query column `{field}` on {}", M::RELATION);
    }

    Ok(())
}

fn write_predicate<M: TableModel>(options: &QueryOptions, all_rows: bool, offset: usize) -> Result<String> {
    options.validate_for_filtered_write()?;
    validate_options::<M>(options)?;
    let (predicate, _) = options.build_where_clause(offset);
    if predicate.is_empty() && !all_rows {
        bail!("write requires at least one filter or explicit all_rows()");
    }

    if !predicate.is_empty() && all_rows {
        bail!("all_rows() cannot be combined with predicates");
    }

    Ok(predicate)
}

pub(crate) fn append_returning<M: QueryModel>(sql: &mut String, returning: bool) {
    if returning {
        sql.push_str(" RETURNING ");
        sql.push_str(&M::COLUMNS.join(", "));
    }
}

pub(crate) async fn query_models<C: Executor + ?Sized, M: FromRow>(
    client: &C,
    sql: &str,
    params: &[&(dyn ToSql + Sync)],
) -> Result<Vec<M>> {
    let rows = client
        .query_rows(sql, params)
        .await
        .context("Failed to execute row query")?;

    rows.iter()
        .map(
            |row| M::from_row(row)
                .context("Row parse error")
        )
        .collect()
}

pub(crate) async fn query_model<C: Executor + ?Sized, M: FromRow>(
    client: &C,
    sql: &str,
    params: &[&(dyn ToSql + Sync)],
) -> Result<M> {
    let row = client.query_row(sql, params)
        .await
        .context("Failed to execute single-row query")?;

    M::from_row(&row)
        .context("Row parse error")
}
