use crate::export::{ExportType, Shape};
use crate::validator::{BaseType, Field, Rule, ValidatorBackend, ValidatorSchema};

/// Emits [valibot](https://valibot.dev) schemas.
pub struct Valibot;

impl ValidatorBackend for Valibot {
    fn file_name(&self) -> &str {
        "schema/schemas.ts"
    }

    fn header(&self) -> String {
        "// Generated by orm from #[api_type] validators. Do not edit.\nimport * as v from \"valibot\";\n\n"
            .to_string()
    }

    fn schema(&self, schema: &ValidatorSchema) -> String {
        if schema.fields.is_empty() {
            return format!("export const {}Schema = v.object({{}});", schema.name);
        }

        let fields = schema
            .fields
            .iter()
            .map(|f| format!("  {}: {},", f.name, field(f)))
            .collect::<Vec<_>>()
            .join("\n");

        format!("export const {}Schema = v.object({{\n{fields}\n}});", schema.name)
    }
}

fn field(f: &Field) -> String {
    let mut pipe: Vec<String> = Vec::new();
    if let BaseType::Uuid = f.base {
        pipe.push("v.uuid()".into());
    }
    if let BaseType::Timestamp = f.base {
        pipe.push("v.isoTimestamp()".into());
    }
    pipe.extend(f.rules.iter().map(rule));

    let base = base(&f.base);
    let mut expr = match pipe.is_empty() {
        true => base,
        false => format!("v.pipe({base}, {})", pipe.join(", ")),
    };

    if f.array {
        expr = format!("v.array({expr})");
    }
    if f.optional {
        expr = format!("v.optional({expr})");
    }
    expr
}

fn base(base: &BaseType) -> String {
    match base {
        BaseType::Bool => "v.boolean()".into(),
        BaseType::Number => "v.number()".into(),
        BaseType::String | BaseType::Timestamp | BaseType::Uuid => "v.string()".into(),
        BaseType::Named(name) => named(name),
        BaseType::Unknown => "v.unknown()".into(),
    }
}

/// A named type resolved against the export registry: an enum renders as a
/// picklist of its wire values — the same values its exported TS union carries,
/// so the two can't drift — and anything else stays unknown.
fn named(name: &str) -> String {
    let variants = inventory::iter::<ExportType>
        .into_iter()
        .find(|export| export.name == name)
        .and_then(|export| match export.shape {
            Shape::Enum(variants) => Some(variants),
            Shape::Struct(_) => None,
        });

    match variants {
        Some(variants) => {
            let values = variants
                .iter()
                .map(|variant| format!("\"{variant}\""))
                .collect::<Vec<_>>()
                .join(", ");
            format!("v.picklist([{values}])")
        }
        None => "v.unknown()".into(),
    }
}

fn rule(rule: &Rule) -> String {
    match rule {
        Rule::Email => "v.email()".into(),
        Rule::Url => "v.url()".into(),
        Rule::MinLength(n) => format!("v.minLength({n})"),
        Rule::MaxLength(n) => format!("v.maxLength({n})"),
        Rule::ExactLength(n) => format!("v.length({n})"),
        Rule::Min(n) => format!("v.minValue({n})"),
        Rule::Max(n) => format!("v.maxValue({n})"),
        Rule::Regex(pattern) => format!("v.regex(new RegExp(\"{}\"))", escape_js(pattern)),
    }
}

fn escape_js(pattern: &str) -> String {
    pattern.replace('\\', "\\\\").replace('"', "\\\"")
}
