use crate::validator::{BaseType, Field, Rule, ValidatorBackend, ValidatorSchema};

/// Emits [valibot](https://valibot.dev) schemas.
pub struct Valibot;

impl ValidatorBackend for Valibot {
    fn file_name(&self) -> &str {
        "schema/schemas.ts"
    }

    fn header(&self) -> String {
        "// Generated by orm from #[api_type] validators. Do not edit.\nimport * as v from \"valibot\";\n\n"
            .to_string()
    }

    fn schema(&self, schema: &ValidatorSchema) -> String {
        let fields = schema
            .fields
            .iter()
            .map(|f| format!("{}: {}", f.name, field(f)))
            .collect::<Vec<_>>()
            .join(", ");

        format!("export const {}Schema = v.object({{ {fields} }});", schema.name)
    }
}

fn field(f: &Field) -> String {
    let mut pipe: Vec<String> = Vec::new();
    if let BaseType::Uuid = f.base {
        pipe.push("v.uuid()".into());
    }
    if let BaseType::Timestamp = f.base {
        pipe.push("v.isoTimestamp()".into());
    }
    pipe.extend(f.rules.iter().map(rule));

    let base = base(&f.base);
    let mut expr = match pipe.is_empty() {
        true => base.to_string(),
        false => format!("v.pipe({base}, {})", pipe.join(", ")),
    };

    if f.array {
        expr = format!("v.array({expr})");
    }
    if f.optional {
        expr = format!("v.optional({expr})");
    }
    expr
}

fn base(base: &BaseType) -> &'static str {
    match base {
        BaseType::Bool => "v.boolean()",
        BaseType::Number => "v.number()",
        BaseType::String | BaseType::Timestamp | BaseType::Uuid => "v.string()",
        BaseType::Unknown => "v.unknown()",
    }
}

fn rule(rule: &Rule) -> String {
    match rule {
        Rule::Email => "v.email()".into(),
        Rule::Url => "v.url()".into(),
        Rule::MinLength(n) => format!("v.minLength({n})"),
        Rule::MaxLength(n) => format!("v.maxLength({n})"),
        Rule::ExactLength(n) => format!("v.length({n})"),
        Rule::Min(n) => format!("v.minValue({n})"),
        Rule::Max(n) => format!("v.maxValue({n})"),
        Rule::Regex(pattern) => format!("v.regex(new RegExp(\"{}\"))", escape_js(pattern)),
    }
}

fn escape_js(pattern: &str) -> String {
    pattern.replace('\\', "\\\\").replace('"', "\\\"")
}
