//! Generates a typed TypeScript HTTP client from the `#[endpoint]`-registered
//! handlers — the endpoint twin of `registry::export_all_types`.
//!
//! The output is a single self-contained `createApi(config)` factory returning
//! one object, nested by the dotted `#[endpoint]` name (`"live.rtc.tracks.close"`
//! -> `api.live.rtc.tracks.close`). It holds no global state, so it's safe to
//! instantiate per-request on the server (SvelteKit / Cloudflare Workers) with
//! the incoming request's `fetch` + cookie header, and stash it on `locals`.
//!
//! Every method returns a `Promise<Result<T, ApiError>>` (our own Result, from
//! `$lib/result`) — transport, HTTP, and request-body validation failures all
//! surface as `err(...)` instead of throwing, so callers never need try/catch.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::Path;

use crate::registry::{EndpointMeta, ValibotSchema};

/// A node in the client object tree: nested `groups` and leaf `methods`
/// (method name -> the rendered arrow function, which may span several lines).
#[derive(Default)]
struct Group {
    groups: BTreeMap<String, Group>,
    methods: BTreeMap<String, String>,
}

impl Group {
    fn insert(&mut self, parts: &[&str], method: String) {
        match parts {
            [last] => {
                self.methods.insert((*last).to_string(), method);
            }
            [head, rest @ ..] => {
                self.groups.entry((*head).to_string()).or_default().insert(rest, method);
            }
            [] => {}
        }
    }

    fn render(&self, out: &mut String, indent: usize) {
        let pad = "  ".repeat(indent);
        for (name, method) in &self.methods {
            // A method body may be multi-line; indent every line to `pad` and
            // hang the trailing comma off the last one.
            let lines: Vec<&str> = method.lines().collect();
            let last = lines.len().saturating_sub(1);
            for (i, line) in lines.iter().enumerate() {
                let comma = if i == last { "," } else { "" };
                if i == 0 {
                    let _ = writeln!(out, "{pad}{name}: {line}{comma}");
                } else {
                    let _ = writeln!(out, "{pad}{line}{comma}");
                }
            }
        }
        for (name, group) in &self.groups {
            let _ = writeln!(out, "{pad}{name}: {{");
            group.render(out, indent + 1);
            let _ = writeln!(out, "{pad}}},");
        }
    }
}

/// Write `<out_dir>/client.ts` from the registered endpoints. `types_prefix` is
/// the import prefix for the ts-rs type modules (e.g. `"."` when co-located, or
/// `"$lib/types"` when the types live in a sibling directory).
pub fn generate_client(out_dir: &str, types_prefix: &str) -> anyhow::Result<()> {
    let mut endpoints: Vec<&EndpointMeta> = inventory::iter::<EndpointMeta>.into_iter().collect();
    endpoints.sort_by_key(|e| e.name);

    let schema_names: BTreeSet<String> =
        inventory::iter::<ValibotSchema>.into_iter().map(|s| s.name.to_string()).collect();

    let mut imports: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut schema_imports: BTreeSet<String> = BTreeSet::new();
    let mut root = Group::default();
    let mut needs_query = false;

    for endpoint in &endpoints {
        for type_ref in [&endpoint.request, &endpoint.query, &endpoint.response].into_iter().flatten() {
            if let Some(path) = (type_ref.ts_output_path)() {
                imports.entry(module_specifier(&path, types_prefix)).or_default().insert((type_ref.ts_name)());
            }
        }
        if endpoint.query.is_some() {
            needs_query = true;
        }

        // If the request type has a valibot schema, validate the body before sending.
        let validated = endpoint.request.as_ref().and_then(|r| {
            let name = (r.ts_name)();
            schema_names.contains(&name).then(|| format!("{name}Schema"))
        });
        if let Some(schema) = &validated {
            schema_imports.insert(schema.clone());
        }

        let parts: Vec<&str> = endpoint.name.split('.').collect();
        root.insert(&parts, render_method(endpoint, validated.as_deref()));
    }

    let needs_validate = !schema_imports.is_empty();

    let mut out = String::from("// Generated by orm from #[endpoint] handlers. Do not edit.\n");
    for (module, names) in &imports {
        let list = names.iter().cloned().collect::<Vec<_>>().join(", ");
        let _ = writeln!(out, "import type {{ {list} }} from \"{module}\";");
    }
    let _ = writeln!(out, "import {{ ok, err, result, type Result }} from \"$lib/result\";");
    if needs_validate {
        let _ = writeln!(out, "import * as v from \"valibot\";");
        let list = schema_imports.iter().cloned().collect::<Vec<_>>().join(", ");
        let _ = writeln!(out, "import {{ {list} }} from \"./schemas\";");
    }

    out.push_str(CONFIG_BLOCK);
    out.push_str("\nexport function createApi(config: ApiConfig = {}) {\n");
    out.push_str(REQUEST_HELPER);
    if needs_validate {
        out.push_str(VALIDATE_HELPER);
        out.push_str(SEND_HELPER);
    }
    if needs_query {
        out.push_str(QUERY_HELPER);
    }
    out.push_str("\n  return {\n");
    root.render(&mut out, 2);
    out.push_str("  };\n}\n\n");
    out.push_str("export type Api = ReturnType<typeof createApi>;\n");

    std::fs::create_dir_all(out_dir)?;
    std::fs::write(Path::new(out_dir).join("client.ts"), out)?;
    Ok(())
}

const CONFIG_BLOCK: &str = r#"
export interface ApiConfig {
  /** API origin, e.g. PUBLIC_SERVICE_URL on Railway. Defaults to same-origin. */
  baseUrl?: string;
  /** fetch to use — pass `event.fetch` on the server (SvelteKit / Workers). */
  fetch?: typeof fetch;
  /** Headers sent on every request, e.g. `{ cookie }` forwarded from the
   *  incoming request during SSR (the browser sends the cookie automatically). */
  headers?: Record<string, string>;
}

export interface ApiError {
  /** HTTP status, 0 for a transport error, or 422 for request validation. */
  status: number;
  message: string;
  /** Field path -> message, present when `status` is 422 (body validation). */
  fields?: Record<string, string>;
}
"#;

const REQUEST_HELPER: &str = r#"  const base = (config.baseUrl ?? "").replace(/\/$/, "");
  const fetchImpl = config.fetch ?? fetch;

  async function request<T>(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<Result<T, ApiError>> {
    const headers: Record<string, string> = { ...config.headers };

    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
    }

    const response = await result(() =>
      fetchImpl(base + path, {
        method,
        credentials: "include",
        headers,
        body: body !== undefined ? JSON.stringify(body) : undefined,
      }),
    );

    if (response.err) {
      const cause = response.error;
      return err({
        status: 0,
        message: `${method} ${path}: ${cause instanceof Error ? cause.message : String(cause)}`,
      });
    }

    const res = response.value;

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      let parsed: { error?: string; fields?: Record<string, string> } | undefined;
      try {
        parsed = body ? JSON.parse(body) : undefined;
      } catch {
        parsed = undefined;
      }
      return err({
        status: res.status,
        message: parsed?.error ?? `${method} ${path} failed (${res.status})${body ? `: ${body}` : ""}`,
        fields: parsed?.fields,
      });
    }

    const text = await res.text();

    return ok(text ? (JSON.parse(text) as T) : (undefined as T));
  }
"#;

const VALIDATE_HELPER: &str = r#"
  function validate(schema: v.GenericSchema, body: unknown): Result<unknown, ApiError> {
    const parsed = v.safeParse(schema, body);

    if (parsed.success) {
      return ok(parsed.output);
    }

    const fields: Record<string, string> = {};
    for (const issue of parsed.issues) {
      fields[v.getDotPath(issue) ?? ""] = issue.message;
    }

    return err({
      status: 422,
      message: "Request validation failed",
      fields,
    });
  }
"#;

const SEND_HELPER: &str = r#"
  function send<T>(
    method: string,
    path: string,
    schema: v.GenericSchema,
    body: unknown,
  ): Promise<Result<T, ApiError>> {
    const valid = validate(schema, body);

    if (valid.err) {
      return Promise.resolve(valid);
    }

    return request<T>(method, path, valid.value);
  }
"#;

const QUERY_HELPER: &str = r#"
  function toQuery(params: Record<string, unknown>): string {
    const search = new URLSearchParams();
    for (const [key, value] of Object.entries(params)) {
      if (value !== undefined && value !== null) search.set(key, String(value));
    }
    const query = search.toString();
    return query ? `?${query}` : "";
  }
"#;

/// The arrow function for one endpoint, formatted across a couple of lines:
///
/// ```ts
/// create: (body: CreateSessionRequest): Promise<Result<LiveSession, ApiError>> =>
///   send<LiveSession>("POST", `/live/sessions`, CreateSessionRequestSchema, body),
/// ```
fn render_method(endpoint: &EndpointMeta, validated: Option<&str>) -> String {
    let mut args: Vec<String> = path_params(endpoint.path).iter().map(|p| format!("{p}: string")).collect();
    if let Some(request) = &endpoint.request {
        args.push(format!("body: {}", (request.ts_name)()));
    }
    if let Some(query) = &endpoint.query {
        args.push(format!("query: {}", (query.ts_name)()));
    }
    let args = args.join(", ");

    let returns = endpoint.response.as_ref().map(|r| (r.ts_name)()).unwrap_or_else(|| "void".into());
    let url = format!(
        "`{}`{}",
        endpoint.path.replace('{', "${"),
        if endpoint.query.is_some() { " + toQuery(query)" } else { "" }
    );
    let method = endpoint.method;
    let signature = format!("({args}): Promise<Result<{returns}, ApiError>> =>");

    match (&endpoint.request, validated) {
        // Validate the body with its schema, then send the validated value.
        (Some(_), Some(schema)) => {
            format!("{signature}\n  send<{returns}>(\"{method}\", {url}, {schema}, body)")
        }
        // Body with no schema — pass it through unchanged.
        (Some(_), None) => format!("{signature}\n  request<{returns}>(\"{method}\", {url}, body)"),
        // No body.
        (None, _) => format!("{signature}\n  request<{returns}>(\"{method}\", {url})"),
    }
}

/// `api/live.ts` -> `<prefix>/api/live` (e.g. `./api/live` or `$lib/types/api/live`).
fn module_specifier(path: &Path, prefix: &str) -> String {
    format!("{}/{}", prefix, path.with_extension("").to_string_lossy().replace('\\', "/"))
}

/// Names of `{param}` segments in a route path, in order.
fn path_params(path: &str) -> Vec<String> {
    path.split('/')
        .filter_map(|seg| seg.strip_prefix('{').and_then(|s| s.strip_suffix('}')))
        .map(str::to_string)
        .collect()
}
