//! Language-neutral type model and the export backend trait.
//!
//! The `#[*_type]` macros register an [`ExportType`] describing each type's
//! shape in a language-independent way. An [`ExportBackend`] renders that model
//! into a target language; [`crate::backend::TypeScript`] is the built-in one.
//! To add a language, implement `ExportBackend` and pass it to
//! [`export_all_types`] — no macro changes needed.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use tracing::info;

/// A field's type, independent of any target language.
pub enum FieldType {
    Bool,
    Number,
    String,
    /// An instant (Rust `DateTime<Utc>`).
    Timestamp,
    Uuid,
    /// An opaque JSON value (Rust `serde_json::Value`).
    Json,
    Array(&'static FieldType),
    /// A reference to another exported type, by name.
    Named(&'static str),
}

pub struct Field {
    pub name: &'static str,
    pub ty: &'static FieldType,
    pub optional: bool,
}

pub enum Shape {
    Struct(&'static [Field]),
    /// A closed set of string values (a Rust enum / union).
    Enum(&'static [&'static str]),
}

/// A type to export, registered by the `#[*_type]` macros via `inventory`.
pub struct ExportType {
    pub name: &'static str,
    /// Logical output path from `export_to`, e.g. `database/bookings.ts`.
    pub path: &'static str,
    /// `///` doc lines (leading space trimmed), rendered as the backend sees fit.
    pub docs: &'static [&'static str],
    pub shape: Shape,
}

inventory::collect!(ExportType);

/// Renders the neutral model into a target language. Implement this to support
/// a new language; the file grouping + import resolution are handled for you.
pub trait ExportBackend {
    /// First line written to every generated file.
    fn header(&self) -> &str {
        "// Generated by orm. Do not edit."
    }
    /// On-disk filename for a logical `path` (default: unchanged).
    fn file_name(&self, path: &str) -> String {
        path.to_string()
    }
    /// A comment block from `///` doc lines, or empty for none.
    fn doc(&self, lines: &[&str]) -> String;
    /// A field type rendered as a language type expression.
    fn type_expr(&self, ty: &FieldType) -> String;
    /// A struct/object type declaration.
    fn struct_decl(&self, name: &str, docs: &str, fields: &[Field]) -> String;
    /// A string-union/enum type declaration.
    fn enum_decl(&self, name: &str, docs: &str, variants: &[&str]) -> String;
    /// An import statement pulling `names` from `module`.
    fn import(&self, module: &str, names: &[&str]) -> String;
}

/// Map of exported type name -> its output file, for resolving references.
pub fn type_paths() -> BTreeMap<&'static str, &'static str> {
    inventory::iter::<ExportType>
        .into_iter()
        .map(|t| (t.name, t.path))
        .collect()
}

/// Drain the registry and write every type into `out_dir` using `backend`,
/// grouping types by file and resolving cross-file references to imports.
pub fn export_all_types(out_dir: &str, backend: &dyn ExportBackend) -> anyhow::Result<()> {
    let types: Vec<&ExportType> = inventory::iter::<ExportType>.into_iter().collect();
    let path_of = type_paths();

    let mut by_file: BTreeMap<&str, Vec<&ExportType>> = BTreeMap::new();
    for t in &types {
        by_file.entry(t.path).or_default().push(t);
    }

    for (path, mut decls) in by_file {
        decls.sort_by_key(|t| t.name);
        let local: BTreeSet<&str> = decls.iter().map(|t| t.name).collect();

        let mut imports: BTreeMap<String, BTreeSet<&str>> = BTreeMap::new();
        for t in &decls {
            for dep in dependencies(&t.shape) {
                if local.contains(dep) {
                    continue;
                }
                let Some(dep_path) = path_of.get(dep) else { continue };

                imports
                    .entry(relative_import(path, dep_path))
                    .or_default()
                    .insert(dep);
            }
        }

        let mut out = format!("{}\n", backend.header());
        for (module, names) in &imports {
            let names: Vec<&str> = names.iter().copied().collect();
            out.push_str(&backend.import(module, &names));
            out.push('\n');
        }
        out.push('\n');

        let bodies: Vec<String> = decls.iter().map(|t| render(backend, t)).collect();
        out.push_str(&bodies.join("\n\n"));
        out.push('\n');

        let file = Path::new(out_dir).join(backend.file_name(path));
        if let Some(parent) = file.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(file, out)?;
    }

    info!("Exported {} type(s)", types.len());
    Ok(())
}

fn render(backend: &dyn ExportBackend, t: &ExportType) -> String {
    let docs = backend.doc(t.docs);
    match &t.shape {
        Shape::Struct(fields) => backend.struct_decl(t.name, &docs, fields),
        Shape::Enum(variants) => backend.enum_decl(t.name, &docs, variants),
    }
}

/// Names of other exported types a shape references (through struct fields).
fn dependencies(shape: &Shape) -> Vec<&'static str> {
    let mut out = Vec::new();
    if let Shape::Struct(fields) = shape {
        for field in *fields {
            collect_named(field.ty, &mut out);
        }
    }
    out
}

fn collect_named(ty: &FieldType, out: &mut Vec<&'static str>) {
    match ty {
        FieldType::Named(name) => out.push(name),
        FieldType::Array(inner) => collect_named(inner, out),
        _ => {}
    }
}

/// Relative module specifier from `from_file` to `to_file`, without the
/// extension — e.g. `api/x.ts` -> `database/y.ts` = `../database/y`.
pub fn relative_import(from_file: &str, to_file: &str) -> String {
    let from: Vec<&str> = strip_ext(from_file).split('/').collect();
    let to: Vec<&str> = strip_ext(to_file).split('/').collect();
    let from_dir = &from[..from.len() - 1];

    let common = from_dir
        .iter()
        .zip(&to[..to.len() - 1])
        .take_while(|(a, b)| a == b)
        .count();

    let mut parts: Vec<String> = match from_dir.len() - common {
        0 => vec![".".into()],
        ups => std::iter::repeat_n("..".to_string(), ups).collect(),
    };
    parts.extend(to[common..].iter().map(|s| s.to_string()));
    parts.join("/")
}

fn strip_ext(path: &str) -> &str {
    path.rsplit_once('.').map_or(path, |(stem, _)| stem)
}
