use std::path::PathBuf;

use tracing::info;

use crate::export::FieldType;

/// A request/response/query type referenced by an endpoint, in the neutral
/// model. The client generator renders it (and resolves imports) via a backend.
pub struct TypeRef {
    pub ty: &'static FieldType,
}

/// One HTTP endpoint, registered by `#[endpoint(METHOD, "/path")]`. Drained by
/// the client generator (see [`crate::client`]) to emit a typed TS client.
pub struct EndpointMeta {
    pub method: &'static str,
    pub path: &'static str,
    pub name: &'static str,
    pub request: Option<TypeRef>,
    pub query: Option<TypeRef>,
    pub response: Option<TypeRef>,
}

inventory::collect!(EndpointMeta);

/// A valibot schema for an `#[api_type]`, derived from the struct's field types
/// and `#[validate(...)]` rules. `build` runs at export time (not macro time) so
/// `regex` rules can read the actual pattern from the compiled `Regex`.
pub struct ValibotSchema {
    pub name: &'static str,
    pub build: fn() -> String,
}

inventory::collect!(ValibotSchema);

/// Write `<out_dir>/schemas.ts` — runtime valibot validators for the api types.
pub fn export_valibot_schemas(out_dir: &str) -> anyhow::Result<()> {
    let mut schemas: Vec<&ValibotSchema> = inventory::iter::<ValibotSchema>.into_iter().collect();
    if schemas.is_empty() {
        return Ok(());
    }
    schemas.sort_by_key(|s| s.name);

    let mut out =
        String::from("// Generated by orm from #[api_type] validators. Do not edit.\nimport * as v from \"valibot\";\n\n");
    for schema in &schemas {
        out.push_str(&format!("export const {}Schema = {};\n", schema.name, (schema.build)()));
    }

    std::fs::create_dir_all(out_dir)?;
    std::fs::write(PathBuf::from(out_dir).join("schemas.ts"), out)?;
    info!("Exported {} valibot schema(s)", schemas.len());
    Ok(())
}
