use std::path::PathBuf;

use tracing::info;
use ts_rs::ExportError;

pub struct TypeExport {
    pub name: &'static str,
    pub export_all: fn() -> Result<(), ExportError>,
}

inventory::collect!(TypeExport);

pub fn export_all_types() -> anyhow::Result<()> {
    for export in inventory::iter::<TypeExport> {
        (export.export_all)().map_err(|e| anyhow::anyhow!("Failed to export {}: {}", export.name, e))?;
        info!("Exported {}", export.name);
    }

    Ok(())
}

/// A request/response/query type referenced by an endpoint, resolved through
/// `ts-rs` so the client generator can emit the right TypeScript name and the
/// import path of the file ts-rs exported it to.
pub struct TypeRef {
    pub ts_name: fn() -> String,
    pub ts_output_path: fn() -> Option<PathBuf>,
}

/// One HTTP endpoint, registered by `#[endpoint(METHOD, "/path")]`. Drained by
/// the client generator (see [`crate::client`]) to emit a typed TS client — the
/// twin of `export_all_types` for endpoints instead of types.
pub struct EndpointMeta {
    pub method: &'static str,
    pub path: &'static str,
    pub name: &'static str,
    pub request: Option<TypeRef>,
    pub query: Option<TypeRef>,
    pub response: Option<TypeRef>,
}

inventory::collect!(EndpointMeta);

/// A valibot schema for an `#[api_type]`, derived from the struct's field types
/// and `#[validate(...)]` rules. `build` runs at export time (not macro time) so
/// `regex` rules can read the actual pattern from the compiled `Regex` via
/// `as_str()` — something only available at runtime.
pub struct ValibotSchema {
    pub name: &'static str,
    pub build: fn() -> String,
}

inventory::collect!(ValibotSchema);

/// Write `<out_dir>/schemas.ts` — runtime valibot validators for the api types,
/// the companion to the ts-rs type files.
pub fn export_valibot_schemas(out_dir: &str) -> anyhow::Result<()> {
    let mut schemas: Vec<&ValibotSchema> = inventory::iter::<ValibotSchema>.into_iter().collect();
    if schemas.is_empty() {
        return Ok(());
    }
    schemas.sort_by_key(|s| s.name);

    let mut out =
        String::from("// Generated by orm from #[api_type] validators. Do not edit.\nimport * as v from \"valibot\";\n\n");
    for schema in &schemas {
        out.push_str(&format!("export const {}Schema = {};\n", schema.name, (schema.build)()));
    }

    std::fs::create_dir_all(out_dir)?;
    std::fs::write(PathBuf::from(out_dir).join("schemas.ts"), out)?;
    info!("Exported {} valibot schema(s)", schemas.len());
    Ok(())
}
